version: 2.1

workflows:
  version: 2
  build_workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    working_directory: ~/SimpleApplication
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - SimpleApplication
